name: "prefect"
description: "A reusable action to install and authenticate prefect cloud"
inputs:
  prefect-api-key:
    description: "API key for Prefect Cloud authentication"
    required: true
runs:
  using: "composite"
  steps:
    - name: install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: install prefect
      run: pip install prefect==2.8.5
      uses: shell
    - name: setup prefect cloud
      run: prefect cloud login --key ${{ inputs.prefect-api-key }}
      uses: shell
