name: "prefect"
description: "A suite of common tools for prefect"
runs:
  using: "composite"
  steps:
    - name: install
      run: |
        sudo apt-get install -y \
          build-essential \
          libssl-dev \
          libffi-dev \
          python3-dev \
          python3-setuptools

        sudo python3 -m pip install prefect

        prefect backend server cloud
        prefect auth login -t ${{ secrets.PREFECT_API_TOKEN }}

      shell: bash
